sudo: required
services:
  - docker

before_install:
  - docker build -t garveworm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run garveworm/react-test npm test -- --coverage

after_success:
  - docker build -t garveworm/multi-client ./client
  - docker build -t garveworm/multi-nginx ./nginx
  - docker build -t garveworm/multi-server ./server
  - docker build -t garveworm/multi-worker ./worker
  # Log into Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push garveworm/multi-client
  - docker push garveworm/multi-nginx
  - docker push garveworm/multi-server
  - docker push garveworm/multi-worker